apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
data:
  PORT: "{{ .Values.port }}"
  PUBLIC_WELCOME_MESSAGE: "{{ .Values.publicWelcomeMessage }}"
