apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - port: 80
      targetPort: {{.Values.port}}
      protocol: TCP
  selector:
    app: "{{ .Release.Name }}"
