name: Continuous integration

on:
  push:
  pull_request:

jobs:
  prettier-check:
    name: Prettier check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm ci
      - name: Run prettier
        run: |
          npm run prettier-check
  eslint-check:
    name: ESLint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm ci
      - name: Run eslint
        run: |
          npm run eslint-check
  jest-check:
    name: Jest check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm ci
      - name: Run Jest
        run: |
          npm run jest-check
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage_report
          path: coverage_report
  npm-audit-check:
    name: NPM audit check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run npm audit
        run: |
          npm run npm-audit-check
  typescript-check:
    name: TypeScript check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm ci
      - name: Run TypeScript
        run: |
          npm run typescript-check
  compile:
    name: Compile
    needs: [eslint-check, jest-check, npm-audit-check, typescript-check]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm ci
      - name: Compile
        run: |
          npm run compile
      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
