env:
  NODE_JS_VERSION: "22.11.0"
jobs:
  prettier_check:
    name: "Prettier check"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"
      - name: "Setup Node.js"
        uses: "actions/setup-node@v4"
        with:
          cache: "npm"
          node-version: "${{env.NODE_JS_VERSION}}"
      - name: "Install the dependencies"
        run: |
          npm ci
      - name: "Run Prettier check"
        run: |
          npm run prettier:check
name: "Continuous integration"
on:
  push:
