name: Dependencies security

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  npm-audit-check:
    name: npm audit check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run npm audit
        run: |
          npm run npm-audit:check
