env:
  ALPINE_VERSION: "3.20"
  NODE_JS_VERSION: "22.11.0"
jobs:
  release:
    name: "Release"
    outputs:
      release_version: "${{steps.remember_release_version.outputs.release_version}}"
    permissions:
      contents: "write"
      pull-requests: "write"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - name: "Setup Node.js"
        uses: "actions/setup-node@v4"
        with:
          cache: "npm"
          node-version: "${{env.NODE_JS_VERSION}}"
      - name: "Configure Git"
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: "Install the dependencies"
        run: |
          npm ci
      - name: "Release to a new branch"
        env:
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
        run: |
          npm run release -- --verbose --ci
      - id: "remember_release_version"
        name: "Remember release version"
        run: |
          echo "release_version=$(node -p 'require("./package.json").version')" >> $GITHUB_OUTPUT
  build_docker_image:
    name: "Build a Docker image"
    needs: [release]
    outputs:
      release_version: "${{needs.release.outputs.release_version}}"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Download the release files"
        uses: "robinraju/release-downloader@v1.10"
        with:
          tag: "${{needs.release.outputs.release_version}}"
          tarBall: true
      - name: "Unpack the release files"
        run: |
          tar -xzf ./${{github.event.repository.name}}-${{needs.release.outputs.release_version}}.tar.gz
      - name: "Remove tarball"
        run: |
          rm ./${{github.event.repository.name}}-${{needs.release.outputs.release_version}}.tar.gz
      - name: "Move the files to the current directory"
        run: |
          shopt -s dotglob
          mv ./${{github.event.repository.owner.login}}-${{github.event.repository.name}}-*/* ./
          shopt -u dotglob
          rm -rf ./${{github.event.repository.owner.login}}-${{github.event.repository.name}}-*/
      - name: "Build a Docker image"
        run: |
          docker build --tag=${{vars.DOCKER_REGISTRY_REPOSITORY_NAME}}:${{needs.release.outputs.release_version}} --file=Dockerfile --build-arg="NODE_JS_VERSION=${{env.NODE_JS_VERSION}}" --build-arg="ALPINE_VERSION=${{env.ALPINE_VERSION}}" .
      - name: "Upload the Docker image as an artifact"
        uses: "ishworkh/container-image-artifact-upload@v1.1.1"
        with:
          image: "${{vars.DOCKER_REGISTRY_REPOSITORY_NAME}}:${{needs.release.outputs.release_version}}"
  publish_to_docker_registry:
    name: "Publish to the Docker registry"
    needs: [build_docker_image]
    runs-on: "ubuntu-latest"
    steps:
      - name: "Download the image"
        uses: "ishworkh/container-image-artifact-download@v1.0.0"
        with:
          image: "${{vars.DOCKER_REGISTRY_REPOSITORY_NAME}}:${{needs.build_docker_image.outputs.release_version}}"
      - name: "Login to the registry"
        uses: "docker/login-action@v3"
        with:
          password: "${{secrets.DOCKER_REGISTRY_PASSWORD}}"
          registry: "${{vars.DOCKER_REGISTRY_HOST}}"
          username: "${{vars.DOCKER_REGISTRY_USERNAME}}"
      - name: "Push the image to the registry"
        run: |
          docker push ${{vars.DOCKER_REGISTRY_HOST}}/${{vars.DOCKER_REGISTRY_REPOSITORY_NAME}}:${{needs.build_docker_image.outputs.release_version}}
name: "Release"
on:
  workflow_dispatch:
